baseURL = "http://www.primerpy.com/"
languageCode = "en-us"
title = "PrimerPy"

theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
googleAnalytics = "UA-103009539-1"

[Params]
  subtitle = "Primer on Data Science Coding"
  logo = "./img/py.png"
  favicon = "./img/py.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
#  gcse = "008288081600836329244:fdefrs0jhtk"
# Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Isaac Zhou"
  email = "isaaczhou85@gmail.com"
  github = "primerpy"
  twitter = "username"
  reddit = "username"
  linkedin = "username"

[[menu.main]]
    identifier = "focus"
    name = "Focus"
    weight = 1

[[menu.main]]
    parent = "focus"
    name = "Data Analysis"
    url = "/tags/data-analysis"
    weight = 10

[[menu.main]]
    parent = "focus"
    name = "Visualization"
    url = "/tags/visualization"
    weight = 11

[[menu.main]]
    identifier = "flow"
    name = "Flow"
    weight = 2
    url = "/tags/flow"       

[[menu.main]]
    parent = "flow"
    name = "Emacs"
    url = "/tags/emacs"
    weight = 20

[[menu.main]]
    parent = "flow"
    name = "Python"
    url = "/tags/python"
    weight = 21

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 7