baseURL = "http://www.primerpy.com/"
languageCode = "en-us"
title = "PrimerPy"

theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "UA-103059971-1"

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  logo = "./img/icon-light.png"
  favicon = "./img/pi-white.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
#  gcse = "008288081600836329244:fdefrs0jhtk"
# Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Isaac Zhou"
  email = "isaaczhou85@gmail.com"
  github = "primerpy"
  twitter = "username"
  reddit = "username"
  linkedin = "username"

[[menu.main]]
    identifier = "flow-focus"
    name = "Flow & Focus"
    weight = 1

[[menu.main]]
    parent = "flow-focus"
    name = "Data Analysis"
    url = "/tags/data-analysis"
    weight = 1

[[menu.main]]
    parent = "flow-focus"
    name = "Visualization"
    url = "/tags/visualization"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 7